name: Daily Scheduled Maintenance
on:
  schedule:
    - cron: 15 0 * * *

jobs:
  create_issue:
    name: Create maintenance window issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      - name: Create maintenance window issue
        uses: imjohnbo/issue-bot@v3.0
        with:
          assignees: ""
          labels: "maintenance"
          title: "Demo maintenance"
          body: |
            <!---
            start: ${{ steps.date.outputs.today }}T10:55:00.00Z
            end: ${{ steps.date.outputs.today }}T11:15:00.00Z
            expectedDown: admin-comms-app-https-admin-demo-greyfinch-com, api, appointments-api, patient-hub-https-hub-demo-greyfinch-com, pms-app-https-app-demo-greyfinch-com
            --->
            ### Daily Maintenance
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
